name: Java CI Build # The name of your workflow, shows up in the Actions tab

# When should this workflow be triggered?
on:
  push: # Trigger on any push to any branch
  pull_request: # Also trigger on any pull request

# The sequence of jobs this workflow will run
jobs:
  build: # This is the name of the job (ID is 'build')
    runs-on: ubuntu-latest # The type of machine to run the job on (Windows, macOS, Ubuntu)

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4 # This is a pre-built action to get your code

      # Step 2: Set up a Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Specify your Java version (11, 17, 21 are common)
          distribution: 'temurin' # This is the Eclipse Temurin JDK, a popular choice

      # Step 3: Compile the code to verify it works
      - name: Compile with Maven
        run: mvn compile --no-transfer-progress # The command to run

      # (Optional) Step 4: Run tests to ensure nothing is broken
      - name: Run tests with Maven
        run: mvn test --no-transfer-progress